# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160120_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniquidId',
            fields=[
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
        ),
    ]
