# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160120_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquidid',
            name='content',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='uniquidid',
            name='name',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
