# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20160120_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniquidId',
        ),
    ]
